name: Develop
on:
  push:
    branches:
      - develop
jobs:
  demo:
    name: Demo
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 14
      - name: Bundle 📦
        run: |
          npm install
          npm run build
      - name: Install and Build 🔧
        run: |
          npm install
          npm run build
        working-directory: demo
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          GITHUB_TOKEN: ${{ secrets.GH_ACTIONS }}
          BRANCH: gh-pages # The branch the action should deploy to.
          FOLDER: demo/build # The folder the action should deploy.
          CLEAN: true # Automatically remove deleted files from the deploy branch
